version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel_network
        ports:
            - "9001:9000"

    webserver:
        image: nginx:latest
        container_name: laravel_nginx
        depends_on:
            - app
        volumes:
            - .:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8080:80"
        networks:
            - laravel_network

    db:
        image: mariadb:latest
        container_name: laravel_mariadb
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: gscolaire
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge
