version: '3.8'

services:
    nextjs:
        build:
            context: ./Nextjs
            dockerfile: Dockerfile
        container_name: nextjs_app
        working_dir: /app
        volumes:
            - ./Nextjs:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        networks:
            - laravel_network

    app:
        build:
            context: ./Laravel
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - ./Laravel:/var/www
        networks:
            - laravel_network
        ports:
            - "9001:9000"

    webserver:
        image: nginx:latest
        container_name: laravel_nginx
        depends_on:
            - app
        volumes:
            - ./Laravel:/var/www
            - ./Laravel/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./Laravel/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8080:80"
        networks:
            - laravel_network

    db:
        image: mariadb:latest
        container_name: laravel_mariadb
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: gscolaire
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"
        networks:
            - laravel_network

    artisan:
        build:
            context: ./Laravel
        command: bash -c "composer install && php artisan migrate && php artisan db:seed"
        volumes:
            - ./Laravel:/var/www
        depends_on:
            - db
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge
